In [220]:
import numpy as np

In [221]:
nd_array = np.linspace(1, 10 , 18, endpoint=False).reshape(3, 6)
print(nd_array)
nd_array[1, 2]
#nd_array

[[1.  1.5 2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5 6.  6.5]
 [7.  7.5 8.  8.5 9.  9.5]]


5.0